/*
 * @Author: EdisonGu
 * @Date: 2022-08-22 23:38:34
 * @LastEditors: EdisonGu
 * @LastEditTime: 2022-09-12 18:40:13
 * @Descripttion: 
 */

import React, { Component } from 'react'
import Head from 'next/head'

interface Iprops {
}

interface Istate {
}

class index extends Component<Iprops, Istate> {
  constructor(props: Iprops) {
    super(props)
    this.state = {
    }
  }
  render(): React.ReactNode {
    return (
      <Head>
        <title>MovieFly</title>
        <meta name="description" content="Generated by create next app" />
        <meta httpEquiv="Cache-Control" content="max-age=7200" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://g.alicdn.com/de/prismplayer/2.12.0/skins/default/aliplayer-min.css" />
        <script charset="utf-8" type="text/javascript" src="https://g.alicdn.com/de/prismplayer/2.12.0/aliplayer-h5-min.js"></script>
      </Head>
    )
 }
}
export default index