/*
 * @Author: EdisonGu
 * @Date: 2022-08-22 23:38:34
 * @LastEditors: EdisonGu
 * @LastEditTime: 2022-08-22 23:39:05
 * @Descripttion: 
 */

import React, { Component } from 'react'
import Head from 'next/head'

interface Iprops {
}

interface Istate {
}

class index extends Component<Iprops, Istate> {
  constructor(props: Iprops) {
    super(props)
    this.state = {
    }
  }
  render(): React.ReactNode {
    return (
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    )
 }
}
export default index